name = "callcenterv3"
main = "src/server/index.ts"
compatibility_date = "2026-07-14"

[ai]
binding = "AI"

[assets]
directory = "./dist"
binding = "ASSETS"

[observability.logs]
enabled = true
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "campaign-db"
database_id = "410a10bb-4a09-43e0-83a1-51b11171d685"
migrations_dir = "migrations"

[[durable_objects.bindings]]
name = "GROUP_COORDINATOR"
class_name = "GroupCoordinator"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GroupCoordinator"]
